name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # --- Python setup ---
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # --- Install backend dependencies ---
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r backend/product_service/requirements.txt
          pip install -r backend/order_service/requirements.txt
          pip install pytest

      # --- Run backend tests ---
      - name: Run backend tests
        run: |
          pytest backend/product_service/tests
          pytest backend/order_service/tests

      # --- Node setup (optional frontend) ---
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: |
          if [ -f frontend/package.json ]; then
            cd frontend
            npm install
          fi

      # --- Docker login to ACR ---
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ env.ACR_USERNAME }}
          password: ${{ env.ACR_PASSWORD }}

      # --- Build Docker images ---
      - name: Build Docker images
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/product_service:latest backend/product_service
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/order_service:latest backend/order_service

      # --- Push Docker images to ACR ---
      - name: Push Docker images
        run: |
          docker push ${{ env.ACR_LOGIN_SERVER }}/product_service:latest
          docker push ${{ env.ACR_LOGIN_SERVER }}/order_service:latest

      # --- Optional: deploy to Azure ---
      - name: Deploy to Azure (optional)
        run: |
          echo "Add your kubectl / azure deployment commands here"

      # --- Logout from Azure ---
      - name: Azure logout
        run: |
          az logout || echo "No active session to logout"
